package com.level11data.databricks.cluster;

public enum TerminationCode {
    USER_REQUEST, JOB_FINISHED, INACTIVITY, CLOUD_PROVIDER_SHUTDOWN, COMMUNICATION_LOST,
    CLOUD_PROVIDER_LAUNCH_FAILURE, SPARK_STARTUP_FAILURE, UNEXPECTED_LAUNCH_FAILURE,
    INTERNAL_ERROR
}